from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, Text, JSON
from sqlalchemy.orm import relationship
from app.database.base import Base


class AIAnalysis(Base):
    """Persisted AI Analysis Records generated by AI_Modules processing."""
    __tablename__ = "ai_analyses"

    id = Column(Integer, primary_key=True, index=True)
    company_id = Column(Integer, ForeignKey("companies.id"), nullable=False, index=True)
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=True, index=True)
    analysis_type = Column(String(50), nullable=False, index=True)  # DOCUMENT, COMPLIANCE, RISK, FRAUD, EXPLANATION
    model_name = Column(String(100), nullable=False, default="surakshit-shram-ai")
    model_version = Column(String(50), nullable=False, default="v2.1-ml-rule-engine")
    risk_score = Column(Float, nullable=True)
    risk_level = Column(String(20), nullable=True)  # LOW, MEDIUM, HIGH, CRITICAL
    confidence = Column(Float, nullable=True)
    status = Column(String(20), nullable=False, default="SUCCESS")  # SUCCESS, PARTIAL, FAILED
    result_data = Column(JSON, nullable=False)  # Complete JSON analysis payload
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), nullable=False)

    company = relationship("Company", backref="ai_analyses")
    document = relationship("Document", backref="ai_analyses")
    creator = relationship("User", backref="ai_analyses")
