"""initial_schema_with_tenant_isolation_and_soft_delete

Revision ID: 39035d482dc7
Revises: 
Create Date: 2026-08-22 06:38:10.586517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39035d482dc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_companies_is_deleted'), 'companies', ['is_deleted'], unique=False)
    op.create_unique_constraint('uq_company_compliance_period', 'compliance_records', ['company_id', 'compliance_type', 'reporting_period'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_constraint('uq_company_compliance_period', 'compliance_records', type_='unique')
    op.drop_index(op.f('ix_companies_is_deleted'), table_name='companies')
    op.drop_column('companies', 'deleted_at')
    op.drop_column('companies', 'is_deleted')
    # ### end Alembic commands ###
