"""add_ai_analyses_table

Revision ID: d92cff49bcb1
Revises: 39035d482dc7
Create Date: 2026-08-23 20:02:23.274069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92cff49bcb1'
down_revision: Union[str, Sequence[str], None] = '39035d482dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_analysis_type'), 'ai_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analyses_company_id'), 'ai_analyses', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_document_id'), 'ai_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_document_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_company_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_type'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
